rollback

diff --git a/.github/workflows/dask_runner_tests.yml b/.github/workflows/dask_runner_tests.yml
--- a/.github/workflows/dask_runner_tests.yml
+++ b/.github/workflows/dask_runner_tests.yml
@@ -87,22 +87,7 @@ jobs:
       - name: Run tests basic windows
         if: startsWith(matrix.os, 'windows')
         working-directory: ./sdks/python
-        shell: bash
-        run: |
-          # 1. Install dependencies from 'commands_pre' in tox.ini
-          pip install "distributed>=2024.4.2,<2024.9.0" "dask>=2024.4.2,<2024.9.0"
-
-          # 2. Run the first test command from tox.ini
-          python apache_beam/examples/complete/autocomplete_test.py
-
-          # 3. Run the dask tests directly, bypassing the broken run_pytest.sh script
-          echo "Running parallel Dask tests (not no_xdist)..."
-          pytest -m "not no_xdist" --junitxml="pytest-dask-parallel.xml" --pyargs apache_beam.runners.dask
-
-          echo "Running sequential Dask tests (no_xdist)..."
-          # Run pytest and allow it to exit with 0 (success) or 5 (no tests found).
-          # Fail on any other exit code.
-          pytest -m "no_xdist" --junitxml="pytest-dask-sequential.xml" --pyargs apache_beam.runners.dask || [ $? -eq 5 ]
+        run: tox -c tox.ini -e ${{ matrix.params.tox_env }}-win-dask
       - name: Upload test logs
         uses: actions/upload-artifact@v4
         if: always()
@@ -110,3 +95,24 @@ jobs:
           name: pytest-${{matrix.os}}-${{matrix.params.py_ver}}
           path: sdks/python/pytest**.xml
 
+
+
+      # - name: Run tests basic windows
+      #   if: startsWith(matrix.os, 'windows')
+      #   working-directory: ./sdks/python
+      #   shell: bash
+      #   run: |
+      #     # 1. Install dependencies from 'commands_pre' in tox.ini
+      #     pip install "distributed>=2024.4.2,<2024.9.0" "dask>=2024.4.2,<2024.9.0"
+
+      #     # 2. Run the first test command from tox.ini
+      #     python apache_beam/examples/complete/autocomplete_test.py
+
+      #     # 3. Run the dask tests directly, bypassing the broken run_pytest.sh script
+      #     echo "Running parallel Dask tests (not no_xdist)..."
+      #     pytest -m "not no_xdist" --junitxml="pytest-dask-parallel.xml" --pyargs apache_beam.runners.dask
+
+      #     echo "Running sequential Dask tests (no_xdist)..."
+      #     # Run pytest and allow it to exit with 0 (success) or 5 (no tests found).
+      #     # Fail on any other exit code.
+      #     pytest -m "no_xdist" --junitxml="pytest-dask-sequential.xml" --pyargs apache_beam.runners.dask || [ $? -eq 5 ]
